ClimaArtifactsHelper.jl/Project.toml, ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl, README.md, aerosol2005/Manifest.toml, aerosol2005/Project.toml, aerosol2005/README.md, aerosol2005/create_artifact.jl
=> Add aerosol2005 and ClimaArtifactsHelper

ClimaArtifactsHelper.jl/Project.toml, ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl, aerosol2005/Manifest.toml, aerosol2005/OutputArtifacts.toml, aerosol2005/create_artifact.jl
A new path to handle artifacts that cannot be uploaded/downloaded.
=> Add handling of larger artifacts

README.md, clm_data/Manifest.toml, clm_data/OutputArtifacts.toml, clm_data/Project.toml, clm_data/README.md, clm_data/create_artifact.jl
Adds the CLM surface data file (at 0.9x1.25 degree resolution) with references for PFT distribution.
README.md
Review checklist
I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.
In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.
----
=> Add README for CLM PFT surface data

ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl, README.md, soil_params_Gupta2020_2022/Manifest.toml, soil_params_Gupta2020_2022/OutputArtifacts.toml, soil_params_Gupta2020_2022/Project.toml, soil_params_Gupta2020_2022/README.md, soil_params_Gupta2020_2022/create_artifacts.jl, soil_params_Gupta2020_2022/utils.jl
Adds a script which creates the soil hydrology parameters at 2.5 degrees resolution artifact. The raw data is assumed to have already been downloaded and instructions on how to do so is included (it is hosted on zenodo). 
- updated README
- add a new artifact and script that creates it.
Review checklist
I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.
In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, …
=> Soil hydrology parameters

README.md, precipitation_obs/Manifest.toml, precipitation_obs/OutputArtifacts.toml, precipitation_obs/Project.toml, precipitation_obs/README.md, precipitation_obs/create_artifact.jl
Add GPCP precipitation data
Checklist:
=> add gpcp precipitation

README.md, cmip_model_rmse/Manifest.toml, cmip_model_rmse/OutputArtifacts.toml, cmip_model_rmse/Project.toml, cmip_model_rmse/README.md, cmip_model_rmse/create_artifact.jl
=> add amip rmse artifact

README.md
=> Update aerosol concentration artifact in README.md

README.md, precipitation_obs/README.md, radiation_obs/Manifest.toml, radiation_obs/OutputArtifacts.toml, radiation_obs/Project.toml, radiation_obs/README.md, radiation_obs/create_artifact.jl
=> add radiation observation

README.md, ozone_concentrations/Manifest.toml, ozone_concentrations/OutputArtifacts.toml, ozone_concentrations/Project.toml, ozone_concentrations/README.md, ozone_concentrations/create_artifact.jl
=> add ozone concentration artifact

ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl, README.md, historical_sst_sic/Manifest.toml, historical_sst_sic/OutputArtifacts.toml, historical_sst_sic/Project.toml, historical_sst_sic/README.md, historical_sst_sic/create_artifact.jl
=> Add sea surface temperature and sea ice concentration

clm_data/README.md, clm_data/create_artifact.jl, clm_data/dominant_mechanism.py, clm_data/dominant_pft.py, clm_data/dominant_root_beta.py, clm_data/pft_variables.py, clm_data/requirements.txt
This updates the clm_data folder to produce an artifact that is the same as what is in /groups/esm/ClimaArtifacts/artifacts/clm_data.
All the scripts used to generate the files on calhpc are copied into the clm_data folder. The pft_variables script is updated to reflect the proper units for medlynslope and medlynintercept. Medlynslope was umol H2O/umol CO2 and is now sqrt(kPa) and medlynintercept was umol H2O and is now umol m^-2 s^-1. 
Previously, create_artifacts.jl downloaded a single surf data file. create_artifact.jl is updated to download two new files that are used to produce the output data. create_artifact.jl also runs several python scripts to produce the output data. The README is updated, but information about some of the vars and files is still missing.
Closes #38 
Checklist: …
=> Update clm_data artifact

aerosol_concentrations/Manifest.toml, aerosol_concentrations/OutputArtifacts.toml, aerosol_concentrations/README.md, aerosol_concentrations/create_artifact.jl, ozone_concentrations/Manifest.toml, ozone_concentrations/OutputArtifacts.toml, ozone_concentrations/README.md, ozone_concentrations/create_artifact.jl
- Raises the top to 80 km
- Increases number of vertical points to 42
- Also produces a lowres version with fewer points and aerosols to be downloaded automatically
=> Update aeorsol_concentration artifact

ozone_concentrations/OutputArtifacts.toml
=> Add higher res ozone file

aerosol_concentrations/OutputArtifacts.toml, aerosol_concentrations/README.md, aerosol_concentrations/create_artifact.jl, historical_sst_sic/Manifest.toml, historical_sst_sic/OutputArtifacts.toml, historical_sst_sic/Project.toml, historical_sst_sic/README.md, historical_sst_sic/create_artifact.jl, ozone_concentrations/OutputArtifacts.toml, ozone_concentrations/README.md, ozone_concentrations/create_artifact.jl
This new artifact can be automatically downloaded and contains 1 year of data at 1/6th resolution.
The hash for the higher res changed because the previous one was wrong. 
I will apply relevant changes downstream
=> Create lower res version of SST and SIC and add more years to other lowres versions

clm_data/OutputArtifacts.toml, clm_data/README.md, clm_data/pft_variables.py
Checklist:
Map of leaf orientation index:
=> Add xl to clm_data

README.md, co2_dataset/Manifest.toml, co2_dataset/OutputArtifacts.toml, co2_dataset/Project.toml, co2_dataset/README.md, co2_dataset/create_artifact.jl
Relates to: [ClimaCore Issue 997](https://github.com/CliMA/ClimaCoupler.jl/issues/997)
Checklist:
=> Add CO2 artifact to ClimaArtifacts

clm_data/OutputArtifacts.toml, clm_data/README.md, clm_data/create_artifact.jl, clm_data/soil_variables.py
A new script is added that generated soil_properties_map.nc. It contains a hard coded table that maps soil color to albedo values. The soil colors are read from surfdata...nc. The new artifact is on box and the server. See maps of new vars below:
(Ocean masked)
(No masks)
Checklist:
=> Add soil_properties_map.nc to clm_data

README.md, bedrock_depth/Manifest.toml, bedrock_depth/OutputArtifacts.toml, bedrock_depth/Project.toml, bedrock_depth/README.md, bedrock_depth/create_artifact.jl
Checklist:
- X] I added a link to the main `README.md` to point to the new artifact
=> add bedrock depth data

era5_cloud/OutputArtifacts.toml
=> add missing OutputArtifacts in era5_cloud

era5_cloud/OutputArtifacts.toml, era5_cloud/create_artifact.jl
ERA5 latitude coordinate is from 90 to -90. We reverse it so that we can use ClimaUtilities.
=> reverse latitude coordinate in era5_cloud

README.md, ilamb_data/OutputArtifacts.toml, ilamb_data/Project.toml, ilamb_data/README.md, ilamb_data/create_artifact.jl, ilamb_data/reverse_gpp_dim.jl
=> Add some datasets from ILAMB

README.md, bonan_richards_eqn/Manifest.toml, bonan_richards_eqn/OutputArtifacts.toml, bonan_richards_eqn/Project.toml, bonan_richards_eqn/README.md, bonan_richards_eqn/create_artifact.jl, bonan_richards_eqn/get_bonan_data.sh
ClimaLand is updated to use this artifact in https://github.com/CliMA/ClimaLand.jl/pull/900
Checklist:
=> add Bonan Richards Equation datasets

README.md, surface_temperatures/LICENSE, surface_temperatures/Manifest.toml, surface_temperatures/OutputArtifacts.toml, surface_temperatures/Project.toml, surface_temperatures/README.md, surface_temperatures/create_artifact.jl
Checklist:
This is an example what the calculated absolute temperature looks like:
=> Add surface temps artifact

README.md, era5_land_forcing_data2008/OutputArtifacts.toml, era5_land_forcing_data2008/Project.toml, era5_land_forcing_data2008/README.md, era5_land_forcing_data2008/create_artifact.jl, era5_land_forcing_data2008/find_correct_order.jl, era5_land_forcing_data2008/get_era5_land_forcing_data_year.py, era5_land_forcing_data2008/postprocess_and_make_weekly_lai_data.jl, era5_land_forcing_data2008/requirements.txt, era5_land_forcing_data2008/thin_and_postprocess_artifact.jl
=> Add ERA5 land forcing data for 2008

README.md, topmodel/OutputArtifacts.toml, topmodel/Project.toml, topmodel/README.md, topmodel/create_artifacts.jl, topmodel/utils.jl
Checklist:
- [N/A I think] If applicable (e.g., for Creative Commons), I added a `LICENSE` file
=> TOPMODEL topographic index

README.md, soilgrids/LICENSE, soilgrids/OutputArtifacts.toml, soilgrids/Project.toml, soilgrids/README.md, soilgrids/combine_and_transform_raw_data.jl, soilgrids/create_artifacts.jl, soilgrids/download_soilgrids.sh, soilgrids/transform_geotiff_to_netcdf.sh, soilgrids/utils.jl
=> Soil grids data

README.md, ozone_concentrations/OutputArtifacts.toml, ozone_concentrations/README.md, ozone_concentrations/create_artifact.jl
=> extend the ozone concentration artifact

README.md, modis_lai/OutputArtifacts.toml, modis_lai/Project.toml, modis_lai/README.md, modis_lai/create_artifacts.jl
Add monthly LAI data for the year 2008 for use by ClimaLand.
Checklist:
=> Add MODIS LAI data for year 2008

README.md, aerosol_concentrations/create_artifact.jl, era5_cloud/OutputArtifacts.toml, era5_cloud/README.md, era5_cloud/create_artifact.jl, era5_cloud/download_era5.py
=> change era5 cloud artifact to hourly data

README.md, merra2_aerosols/Manifest.toml, merra2_aerosols/OutputArtifacts.toml, merra2_aerosols/Project.toml, merra2_aerosols/README.md, merra2_aerosols/create_artifact.jl, merra2_aerosols/download_utils.jl, merra2_aerosols/processing_utils.jl
=> Add MERRA-2 aerosols artifact

README.md, water_conservation_test/Manifest.toml, water_conservation_test/OutputArtifacts.toml, water_conservation_test/Project.toml, water_conservation_test/README.md, water_conservation_test/create_artifact.jl, water_conservation_test/run_water_conservation_exp.sh, water_conservation_test/water_conservation_exp.jl
I tried out running the `water_conservation_exp.jl` script with different timesteps, and compared each of them to the existing Box artifacts we've been using up until now. Here are the RMSEs we see for each of the timesteps I tested:
```
julia> rmse_dirichlet_dt0p001
4.6405145708886875e-6
julia> rmse_flux_dt0p001
6.516596182265861e-7
julia> rmse_dirichlet_dt0p01
4.6477910453786595e-6
julia> rmse_flux_dt0p01
6.596731926966611e-7
julia> rmse_dirichlet_dt0p1 = rmse(dt0p1_soln_dirichlet, ref_soln_dirichlet)
4.648181924152328e-6
julia> rmse_flux_dt0p1 = rmse(dt0p1_soln_flux, ref_soln_flux)
6.601440537959183e-7
```
Using `dt = 0.001` is very slow to run (~48 hours), while `dt = 0.01` takes around 4-8 hours. Since the RMSE comparing to the previous artifact is similar between the two, I'm using …
=> add water_conservation_test artifact

clm_data/Manifest.toml, clm_data/OutputArtifacts.toml, clm_data/README.md, clm_data/create_artifact.jl, clm_data/dominant_pft.py, clm_data/pft_variables.py, clm_data/soil_variables.py
Add a higher resolution clm_data artifact
Plots comparing the new high-res data and old artifact 
are available [here](https://caltech.box.com/s/rxpieiacak0rq2lgyjgjsrwetkksca9t)
Works towards closing [issue](https://github.com/CliMA/ClimaLand.jl/issues/999) 
Accompanying ClimaLand [PR}(https://github.com/CliMA/ClimaLand.jl/pull/1007)
Checklist:
=> Add higher resolution clm_data artifact

merra2_aerosols/OutputArtifacts.toml, merra2_aerosols/README.md, merra2_aerosols/create_artifact.jl, merra2_aerosols/download_utils.jl, merra2_aerosols/processing_utils.jl
Change conversion from model levels to
elevation to use the hydrostatic equation.
The new mean relative error is -0.034.
=> Update MERRA2 Aerosol Artifact

README.md
This PR adds instructions to obtain artifacts for users without access to the Caltech resources.
Closes #11
=> Add documentation for external users
