CliMA/ClimaArtifacts

- aerosol2005/create_artifact.jl
The original link points to a different file.
> Update file_url in aerosol2005

- README.md
- atmos_held_suarez_obs/Manifest.toml
- atmos_held_suarez_obs/OutputArtifacts.toml
- atmos_held_suarez_obs/Project.toml
- atmos_held_suarez_obs/README.md
- atmos_held_suarez_obs/create_artifact.jl
- atmos_held_suarez_obs/model_config.yml
- atmos_held_suarez_obs/run_model.jl
Adds calibration artifacts for ClimaAtmos. See README for more details
Checklist:
> Add data for reproducing ClimaAtmos Held-Suarez perfect model calibration

- README.md
- snowmip/Manifest.toml
- snowmip/OutputArtifacts.toml
- snowmip/Project.toml
- snowmip/README.md
- snowmip/create_artifacts.jl
Adds the ESM-SnowMIP data - met and snow data for 10 sites, along with some site metadata.
Checklist:
> added ESM-SnowMIP data

- cmip_model_rmse/OutputArtifacts.toml
- cmip_model_rmse/create_artifact.jl
> correct the link in model rmse artifact

- snowmip/OutputArtifacts.toml
- snowmip/create_artifacts.jl
Updates the snowmip artifact so that the metadata includes the start and end dates of the data.
Checklist:
- [N/A] I created a new folder `$artifact_name`
- [N/A] I added a `README.md` in that that folder that
- [N/A] describes the data and processing done to it
- [N/A] lists the sources of the raw data
- [N/A] lists the required citation, licenses
- [N/A] If applicable (e.g., for Creative Commons), I added a `LICENSE` file
- [N/A] I added a link to the main `README.md` to point to the new artifact
> update to include new site data in meta data file

- ClimaArtifactsHelper.jl/Project.toml
- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
Helper function to fetch one single file. Example:
```
using ClimaArtifactsHelper
const FILE_URL = "https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/surfdata_map/surfdata_0.9x1.25_hist_17pfts_nocft_CMIP6_simyr1700_c230809.nc"
const FILE_PATH = "surfdata_0.9x1.25_hist_17pfts_nocft_CMIP6_simyr1700_c230809.nc"
create_artifact_guided_one_file(FILE_PATH; artifact_name = basename(@__DIR__), file_url = FILE_URL)
```
> Add create_artifact_guided_one_file

- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
- radiation_obs/Manifest.toml
- radiation_obs/OutputArtifacts.toml
- radiation_obs/Project.toml
- radiation_obs/README.md
- radiation_obs/create_artifact.jl
Update the radiation observation artifact to include surface radiative fluxes. The artifact is also much bigger and not downloadable now because of higher resolution. Also fixes create_artifact_guided_one_file.
Checklist:
> update radiation observation

- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
- README.md
- aerosol_concentrations/create_artifact.jl
- ozone_concentrations/create_artifact.jl
Artifacts have started having a `lowres` version. This flag allows one `create_artifact` file to create multiple artifacts.
Closes #43
> Add append option to create_artifact_guided

- README.md
- earth_orography/OutputArtifacts.toml
- earth_orography/Project.toml
- earth_orography/README.md
- earth_orography/create_artifact.jl
Current access to topography artifacts in our repositories is restricted to downsampled ETOPO1 (deprecated) data. This artifact addition introduces the ETOPO2022 dataset for use with the ClimaUtilities SpaceVaryingInputs regridding tools. 
Checklist:
> ETOPO2022 orography (ice-surface) 

- README.md
- modis_clumping_index/OutputArtifacts.toml
- modis_clumping_index/Project.toml
- modis_clumping_index/README.md
- modis_clumping_index/create_artifacts.jl
This PR adds a new artifact for global clumping index, used by ClimaLand. 
The corresponding changes in ClimaLand are found [here](https://github.com/CliMA/ClimaLand.jl/pull/863)
Checklist:
> Add global foliage clumping index data derived from MODIS

- precipitation_obs/Manifest.toml
- precipitation_obs/OutputArtifacts.toml
- precipitation_obs/README.md
- precipitation_obs/create_artifact.jl
The new data is from the NOAA rather than the files from caltech data for "Error analysis of climate models...". It contains all the same data as the old artifact, except with data for 2023-present.
The old artifact is still on box, and the new artifact has v2 appended to its name. The new data has a different file name as well.
Checklist:
> Update precipitation_obs artifact data and readme

- README.md
- twostr_test/LICENSE
- twostr_test/OutputArtifacts.toml
- twostr_test/Project.toml
- twostr_test/README.md
- twostr_test/create_artifacts.jl
- twostr_test/gen_2str_data.py
Move TwoStream test data to ClimaArtifacts to allow removal of ArtifactWrappers from ClimaLand.
Corresponding changes to ClimaLand are [here](https://github.com/CliMA/ClimaLand.jl/pull/910).
Checklist:
> add TwoStream test data artifact

- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
Replace `Base.cp` with run(...) on non-Windows operating systems.
`Base.cp` seems to have a bug when copying large files. Using `run` fixes this behaviour.
This fixes the bug mentioned in https://github.com/CliMA/ClimaArtifacts/pull/64
Checklist:
> Replace `Base.cp` with run(...).

- README.md
- atmos_dyamond_summer/OutputArtifacts.toml
- atmos_dyamond_summer/Project.toml
- atmos_dyamond_summer/README.md
- atmos_dyamond_summer/create_artifact.jl
Upload DYAMOND summer initial conditions.
Checklist:
> DYAMOND summer initial conditions

- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
Previously, `create_artifact_guided` would warn that OutputArtifacts.toml is being overwritten whenever append was true, and never warn about overwritting when append was false. This fixes it by inverting the append check.
Closes #71
> Fix OutputArtifact.toml overwritten warning logic

- era5_land_forcing_data2008/OutputArtifacts.toml
- era5_land_forcing_data2008/README.md
- era5_land_forcing_data2008/postprocess_and_make_weekly_lai_data.jl
- era5_land_forcing_data2008/thin_and_postprocess_artifact.jl
Compression doubles the size of the file, but makes running the simulation much faster.
Checklist:
> Remove compression for ERA5 forcing data for land

- ClimaArtifactsHelper.jl/src/ClimaArtifactsHelper.jl
- README.md
- aerosol_concentrations/create_artifact.jl
- bedrock_depth/create_artifact.jl
- cesm2_albedo/create_artifact.jl
- cfsite_gcm_forcing/create_artifact.jl
- clm_data/create_artifact.jl
- co2_dataset/create_artifact.jl
- earth_orography/create_artifact.jl
- historical_sst_sic/create_artifact.jl
- ilamb_data/create_artifact.jl
- landsea_mask/create_artifacts.jl
- ozone_concentrations/create_artifact.jl
- precipitation_obs/create_artifact.jl
- snowmip/create_artifacts.jl
- surface_temperatures/create_artifact.jl
There are two callbacks in this PR. The first only prints the download progress, while the other also prints the download rate.
For both, total size is printed as  MB as an int if it is less than 1 GB, and GB with 2 decimal places otherwise. The same applies to dowloaded size and download rate.
The second callback is created with the function `create_download_rate_callback` which returns
a function. The callback calculates the
download rate over an interval, and prints the result at the end of
the interval. It also prints download progress. This callback
uses a closure to keep track of the time and bytes downloaded
at the end of the previous interval. If this callback is good,
then we can probably remove `download_progress_callback` from this PR.
I considered creating a wrapper for the …
> Add download callback to ClimaArtifactsHelper

- era5_monthly_averages_2008/Manifest.toml
- era5_monthly_averages_2008/OutputArtifacts.toml
- era5_monthly_averages_2008/create_artifact.jl
- era5_monthly_averages_2008/subset_of_data.jl
- era5_monthly_averages_pressure_levels_1979_2024/Manifest.toml
- era5_monthly_averages_pressure_levels_1979_2024/create_artifact.jl
- era5_monthly_averages_single_level_1979_2024/Manifest.toml
- era5_monthly_averages_single_level_1979_2024/OutputArtifacts.toml
- era5_monthly_averages_single_level_1979_2024/process_downloads.jl
Reduces compression levels in era5_monthly_averages_2008, era5_monthly_averages_pressure_levels_1979_2024, and  era5_monthly_averages_single_level_1979_2024. The compression level was determined using a script that profiles the size of the dataset at each compression level, and the time it takes to read a variable. 
Closes #85
> Reduce compression on era5 monthly averages

- README.md
- forty_yrs_era5_land_forcing_data/Manifest.toml
- forty_yrs_era5_land_forcing_data/OutputArtifacts.toml
- forty_yrs_era5_land_forcing_data/Project.toml
- forty_yrs_era5_land_forcing_data/README.md
- forty_yrs_era5_land_forcing_data/combine_rate_and_inst.jl
- forty_yrs_era5_land_forcing_data/create_artifact.jl
- forty_yrs_era5_land_forcing_data/find_corrupted_and_missing_nc_files.jl
- forty_yrs_era5_land_forcing_data/get_era5_land_forcing_data.py
- forty_yrs_era5_land_forcing_data/postprocess_and_make_weekly_lai_data.jl
- forty_yrs_era5_land_forcing_data/postprocess_artifact.jl
- forty_yrs_era5_land_forcing_data/requirements.txt
This PR adds forty years of ERA5 forcing data.
The ERA5 forcing data is at `/net/sampo/data1/era5/forty_yrs_era5_land_forcing_data/forty_yrs_era5_land_forcing_data_artifact`. As of now, it will not be moved to the cluster, because it is around 1TB.
Checklist:
> Add forty years of ERA5 forcing data

- forty_yrs_era5_land_forcing_data/Manifest.toml
- forty_yrs_era5_land_forcing_data/README.md
- forty_yrs_era5_land_forcing_data/combine_rate_and_inst.jl
- forty_yrs_era5_land_forcing_data/create_artifact.jl
- forty_yrs_era5_land_forcing_data/find_corrupted_and_missing_nc_files.jl
- forty_yrs_era5_land_forcing_data/get_era5_land_forcing_data.py
- forty_yrs_era5_land_forcing_data/thin_and_postprocess_artifact.jl
- forty_yrs_era5_land_forcing_data/unzip_era5_data.py
I made the following updates to the artifact:
1. Add code to unzip and rename files due to changes in the Copernicus backend.
2. Change Manifest.toml to use a relative path for ClimaArtifactsHelper.jl.
3. Remove functionality to download rate and instantaneous variables separately. This is because the Copernicus backend fixed the issue of variables not being downloaded by forcing the rate and instantaneous variables to be downloaded separately.
4. Add renaming of rate variables to the names before the change to the Copernicus backend to maintain backward compatibility  with ClimaLand.
> Update artifact to get forty years of ERA5 data

- README.md
- topo_drag/Manifest.toml
- topo_drag/OutputArtifacts.toml
- topo_drag/Project.toml
- topo_drag/README.md
- topo_drag/create_artifact.jl
See [issue](https://github.com/CliMA/ClimaAtmos.jl/issues/3501)
Checklist:
> Add topo drag artifact

- era5_cloud/OutputArtifacts.toml
- era5_cloud/README.md
- era5_cloud/create_artifact.jl
- era5_cloud/download_era5.py
Adds relative humidity to both the era5_cloud era5_cloud_lowres artifacts.
Accompanying ClimaAtmos [PR](https://github.com/CliMA/ClimaAtmos.jl/pull/3619) 
Checklist:
> Add relative humidity to era5_cloud

- clm_data/OutputArtifacts.toml
- clm_data/README.md
- clm_data/create_artifact.jl
- clm_data/pft_variables.py
See accompanying ClimaLand [PR](https://github.com/CliMA/ClimaLand.jl/pull/1007)
Adds Canopy height to both clm data artifacts as `z_top`. 
The `MONTHLY_MEAN_TOP` is a 4D variable on Lon, lat, time, and pft.
The dominant pft is taken, and time is averaged across the months. Averaging the time
is equivalent to just selecting a time, because even though there is a time dim, there is no variance across time
In the 0.125x0.125 surface data file, the `MONTHLY_MEAN_TOP` is zero everywhere. Because of this,
when creating the 0.125x0.125 pft data, the script uses the closest lon and lat from `MONTHLY_MEAN_TOP ` in the 0.9x1.25 surface data file to calculate `z_top` (still uses dominant PFT from 0.125x0.125 surface data file). 
Also rename the low res artifact from clm_data
to clm_data_0.9x1.25 …
> Add z_top to clm artifacts and rename

- README.md
- era5_lai_covers/Manifest.toml
- era5_lai_covers/OutputArtifacts.toml
- era5_lai_covers/Project.toml
- era5_lai_covers/README.md
- era5_lai_covers/create_artifact.jl
- era5_lai_covers/get_era5_lai_covers.py
- era5_lai_covers/remove_time.jl
This PR adds the LAI cover artifact which is needed for this [issue](https://github.com/CliMA/ClimaLand.jl/issues/1004) in ClimaLand.
Checklist:
> Add LAI cover artifact

- README.md
- soil_ic_2008_50m/Manifest.toml
- soil_ic_2008_50m/OutputArtifacts.toml
- soil_ic_2008_50m/Project.toml
- soil_ic_2008_50m/README.md
- soil_ic_2008_50m/create_artifacts.jl
Checklist:
- [N/A] lists the required citation, licenses
- [N/A] If applicable (e.g., for Creative Commons), I added a `LICENSE` file
- [N/A] I added the scripts that retrieve, process, and produce the artifact
> Add spun up soil IC as artifacts

- README.md
- modis_lai/OutputArtifacts.toml
- modis_lai/README.md
- modis_lai/create_artifacts.jl
This very simple PR adds MODIS LAI for years 2000-2020. Previously, we only had 2008. This is the full range of years available from the gridding machine.
Checklist:
> Add additional years of MODIS LAI data (2000-2020)

- era5_lai_covers/OutputArtifacts.toml
- era5_lai_covers/README.md
This need to be updated because I deleted the original folder while trying to diagnose the issue with Box.
For some reason, the SHA256 changes, but I think the LAI covers downloaded from ERA5 change since the script was not modified in any way.
> Update ERA5 LAI covers artifact

- earth_orography/Manifest.toml
- earth_orography/README.md
- earth_orography/create_artifact.jl
This PR does **not** add a new artifact.
While attempting to generate and upload the ETOPO topography artifact, I encountered an issue related to an unregistered package:
```bash
Updating registry at ~/.julia/registries/General.toml
ERROR: expected package ClimaArtifactsHelper [6ffa2572] to be registered
```
The updated `earth_orography/README.md` now includes guidance on how to resolve this by using `Pkg.develop`.
The script `earth_orography/create_artifact.jl` previously threw an error if the dataset had already been downloaded, and the packing or upload step failed. This forced users to manually delete the data and rerun the script:
```bash
ERROR: LoadError: ArgumentError: 'earth_orography_30arcsec_artifact/ETOPO_2022_v1_30s_N90W180_surface.nc' exists. force=true is required ...
```
I …
> earth_orography: Skip copy if file exists; update README

- soil_ic_2008_50m/OutputArtifacts.toml
This updates the artifact for our spun up IC using https://buildkite.com/clima/climaland-long-runs/builds/4035
Checklist:
- [N/A] I created a new folder `$artifact_name`
- [N/A] I added a `README.md` in that that folder that
- [N/A] describes the data and processing done to it
- [N/A] lists the required citation, licenses
- [N/A] If applicable (e.g., for Creative Commons), I added a `LICENSE` file
- [N/A] I added the scripts that retrieve, process, and produce the artifact
- [N/A] I added the environment used for such scripts (typically, `Project.toml`
- [N/A] I added a link to the main …
> updated soil initial conditions using long run 4035
